name: BlockedIn
description: $description
version: '${version}'

main: org.nordiumm.blockedin.BlockedIn
api-version: '26.2'
load: POSTWORLD

authors: [ Nordiumm ]

website: https://github.com/Nordiumm/BlockedIn

commands:
  blockedin:
    description: BlockedIn command

permissions:
  blockedin.admin:
    description: Allows access to BlockedIn admin commands
    default: op